# Generated by Django 5.2.4 on 2025-11-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
    ]
